version_config_file: "v1.0"

# ========================
# Configuração de Fonte
# ========================
source:
  path_blob: "abfss://${container}@${storage_account}.dfs.core.windows.net/"
  directory: "raw_compass/${directory_application}"
  format: "${format}"                  # Formato: csv, parquet, json
  delimiter: "${delimiter}"            # Separador CSV
  header: "${header}"                  # CSV com cabeçalho
  encoding: "utf-8"                    # Encoding
  compression: "${compression}"        # Compressões: gzip (.gz), zip (.zip), snappy
  date_partition_column: "${date_partition_column}"

# ========================
# Configuração do Alvo
# ========================
target:
  path_blob: "abfss://${container}@${storage_account}.dfs.core.windows.net/"
  directory: "b_compass/"
  format: "delta"                 # Bronze → Delta Lake
  mode: "overwrite"               # overwrite, append, merge
  partitionBy: ["${partitionBy}"] # Colunas de partição

# ========================
# Governança / Catálogo
# ========================
governance:
  database: "b_compass"
  table: "${table}"
  version: "${version_config_file}"
  description: "Bronze layer ${directory_application} reviews"
  retention_days: 7
  owner_team: "${sigla}"                  # equipe responsável
  pii: "${pii}"                              # dado sensível?
  sla: "D+1"                              # SLA de ingestão


# ========================
# Telemetria / Observabilidade
# ========================
telemetry:
  active: "${telemetry}"

default_telemetry: |
  {
    "owner": {
      "sigla": "${sigla}",
      "projeto": "${projeto}",
      "layer_lake": "${layer_lake}"
    },
    "valid_data": {
      "count": ${count_valid},
      "percentage": ${percentage_valid}
    },
    "invalid_data": {
      "count": ${count_invalid},
      "percentage": ${percentage_invalid}
    },
    "total_records": ${total_records},
    "total_processing_time": ${total_processing_time},
    "validation_results": ${validation_metrics},
    "success_count": ${success_count},
    "error_count": ${error_count},
    "type_client": "${type_client}",
    "source": {
      "app": "${id_app}",
      "search": "${search}"
    },
    "_ts": {
      "compass_start_ts": "${start_ts}",
      "compass_end_ts": "${end_ts}"
    },
    "timestamp": "${timestamp}"
  }

# ========================
# Fallback
# ========================
fallback:
  create_empty_if_missing: "${create_empty_if_missing}"

# ========================
# Schema
# ========================
schema:
  control_database: "control"
  control_filter_reference: "${application_control}"